### PR TITLE
Upgrade to support .NET 9 and remove support for .NET 6 & 7

### PR DESCRIPTION
**Pull request by mpekurny**

### CODE REVIEW

**Review by sriv — APPROVED** [review]

**Comment by sriv** [comment]
oh drat - I forgot labelling it a release candidate again. @mpekurny - are you planning any more changes in this repo? if not I will trigger a manual release

**Comment by mpekurny** [comment]
I am working on some additional changes, but they are not ready and I was not planning on pushing them for a while.

**Comment by mpekurny** [comment]
Unless you already manually kicked it off, I have the changes ready, so I am going to push it up.

**Comment by sriv** [comment]
Please raise a PR with your changes. I need a new token to do this manually, so I haven't gotten to it yet.

**Pull request merged**
